### ISSUE TITLE
Not working with .net core 3.0

### ISSUE THREAD

**Issue by saifkbr** [fpanaccia/Wkhtmltopdf.NetCore.Example#2]
Hi fpanaccia,

Great solution however it doesn't work with .net ocre 3.0. 

I wonder if we can get .net core 3.0 compatible package of it.

Regards,
MS

**Comment by fpanaccia** [comment]
Hi, have you tried this version?

https://www.nuget.org/packages/Wkhtmltopdf.NetCore/3.0.1-preview

Regards!

**Comment by fpanaccia** [comment]
Also, there is the branch named "feature/3.0" https://github.com/fpanaccia/Wkhtmltopdf.NetCore.Example/tree/feature/3.0 which seems to be wokring, if you have any issue with this one, please let me know

Regards

**Comment by saifkbr** [comment]
Thanks for your response and I will have a look and let you know if there is any issues.

Regards,

**Comment by saifkbr** [comment]
Hi, following link is working fine for me.
https://github.com/fpanaccia/Wkhtmltopdf.NetCore.Example/tree/feature/3.0

Thanks again,

**Comment by fpanaccia** [comment]
no problem!
