### ISSUE TITLE
Adding page orientation as an input option

### ISSUE THREAD

**Issue by jamiehaywood** [fpanaccia/Wkhtmltopdf.NetCore.Example#3]

**Comment by jamiehaywood** [comment]
On the WKHTML docs there's the option to add page orientation as an input. Is this possible with your solution? 

Cheers

**Comment by fpanaccia** [comment]
Hi, sorry for the delay, it could be possible, i guess i could do some modifications to make it work.

When are you gonna need this?
Also if you wanna, feel free to do the modifications required in the library, currently i do not have a lot of free time

Regards!

**Comment by fpanaccia** [comment]
Hi @jamiehaywood, sorry for the delay, i have been a rough couple of weeks.

I just pushed a new version which allows to set the parameters you send to wkhtml, you can look it up right here https://github.com/fpanaccia/Wkhtmltopdf.NetCore.Example/blob/master/Rotativa/Controllers/TestViewsController.cs line 139.

Regards!
