### ISSUE TITLE
How i can add arguments to wkhtmltopdf commands?

### ISSUE THREAD

**Issue by ShamanNark** [fpanaccia/Wkhtmltopdf.NetCore.Example#4]
Hi, great work.
I need set -margin-left 0mm  --margin-right 0mm in command arguments. How can i do this?

**Comment by fpanaccia** [comment]
Hi @ShamanNark 

I just pushed a new versionof the library which allow to set the arguments you want, you can look it up right here https://github.com/fpanaccia/Wkhtmltopdf.NetCore.Example/commit/32377cc2c0db8c90e857e765a011e984013de7a6
