### ISSUE TITLE
How can I add arguments for input fields

### ISSUE THREAD

**Issue by kfaRabi** [fpanaccia/Wkhtmltopdf.NetCore.Example#8]
Hi

I want to add `--enable-forms` flag in ConvertOptions. Is there any way to do it right now?

TIA

**Comment by MoronicMcFry** [comment]
I was wondering the same other Page Options like --run-script <js> and --javascript-delay flags. You could probably do so by extending the ConvertOptions class and adding the OptionFlag attribute to an according property. Unfortunately those are internal and therefore not accessible from outside the assembly.

**Comment by fpanaccia** [comment]
Hi! sorry for the delay, as @MoronicMcFry says, the library will need those flags, if you have some examples i could add it to the library and to the example project by the weekend

**Comment by kfaRabi** [comment]
I do not have any specific examples actually. The template I am converting to pdf has a few input fields. It would be nice if the input fields remain editable once converted to pdf.

I guess a simple template that contains an HTML form (and maybe some JS) will be a good fit for the example project.

Please let me know if in any way I can contribute to the project. I will be happy to do so, although I am totally new to dotnet world.

**Comment by fpanaccia** [comment]
Hi! sorry for the delay...it has been a rough couple of weeks....i dont know if you fixed it, but i open the ConvertOptions and OptionFlag....if you wanna see how to use the "--enable-forms" go to this line https://github.com/fpanaccia/Wkhtmltopdf.NetCore.Example/blob/master/Rotativa/Controllers/TestViewsController.cs#L277

**Comment by kfaRabi** [comment]
Hi! Thank you so so much for taking the time to add this option. This is going to save some of my time and a good amount of money.
